Repository dnd-over-time/over-time-server, pull requests merged in 2025-05, with the labels that each got.

#2 docs : PR 템플릿 추가
  pull_request_template.md
Labels: docs

#3 Junwon
  pull_request_template.md
  src/main/resources/logback-spring.xml
Labels: docs, feat

#4 feat : 카카오 로그인 기능 구현
  build.gradle.kts
  src/main/java/com/server/overtime/member/ctrl/MemberCtrl.java
  src/main/java/com/server/overtime/member/ctrl/req/AdminKey.java
  src/main/java/com/server/overtime/member/ctrl/req/RegisterReq.java
  src/main/java/com/server/overtime/member/ctrl/res/MemberRowIdRes.java
  src/main/java/com/server/overtime/member/dao/MemberJpaRepository.java
  src/main/java/com/server/overtime/member/dao/MemberRepository.java
  src/main/java/com/server/overtime/member/dao/entity/MemberEntity.java
  src/main/java/com/server/overtime/member/exception/AdminErrorCode.java
  src/main/java/com/server/overtime/member/exception/AdminException.java
  src/main/java/com/server/overtime/member/exception/KakaoErrorCode.java
  src/main/java/com/server/overtime/member/exception/KakaoException.java
  src/main/java/com/server/overtime/member/exception/MemberErrorCode.java
  src/main/java/com/server/overtime/member/exception/MemberException.java
  src/main/java/com/server/overtime/member/kakao/KakaoTokenInfo.java
  src/main/java/com/server/overtime/member/kakao/KakaoUserInfo.java
  src/main/java/com/server/overtime/member/sv/KakaoSv.java
  src/main/java/com/server/overtime/member/sv/MemberSv.java
Labels: feat

#6 marker, content api 구현
  src/main/java/com/server/overtime/content/controller/ContentController.java
  src/main/java/com/server/overtime/content/dto/ContentRequest.java
  src/main/java/com/server/overtime/content/dto/ContentResponse.java
  src/main/java/com/server/overtime/content/entity/Content.java
  src/main/java/com/server/overtime/content/repository/ContentRepository.java
  src/main/java/com/server/overtime/content/service/ContentService.java
  src/main/java/com/server/overtime/marker/controller/MarkerController.java
  src/main/java/com/server/overtime/marker/dto/MarkerRequest.java
  src/main/java/com/server/overtime/marker/dto/MarkerResponse.java
  src/main/java/com/server/overtime/marker/entity/Marker.java
  src/main/java/com/server/overtime/marker/repository/MarkerRepository.java
  src/main/java/com/server/overtime/marker/service/MarkerService.java
Labels: feat

#7 feat : presigned url 구현
  build.gradle.kts
  src/main/java/com/server/overtime/config/S3Config.java
  src/main/java/com/server/overtime/s3/ctrl/TestS3Controller.java
  src/main/java/com/server/overtime/s3/ctrl/req/GetPresignedUrlReq.java
  src/main/java/com/server/overtime/s3/ctrl/res/PresignedUrlRes.java
  src/main/java/com/server/overtime/s3/sv/FileService.java
Labels: feat

#9 feat : 북마킹된 컨텐츠 조회 추가
  src/main/java/com/server/overtime/bookmark/dao/BookmarkRepository.java
  src/main/java/com/server/overtime/bookmark/entity/Bookmark.java
  src/main/java/com/server/overtime/bookmark/sv/BookmarkSv.java
  src/main/java/com/server/overtime/content/controller/ContentController.java
  src/main/java/com/server/overtime/content/repository/ContentRepository.java
  src/main/java/com/server/overtime/content/service/ContentService.java
  src/main/java/com/server/overtime/marker/controller/MarkerController.java
  src/main/java/com/server/overtime/marker/repository/MarkerRepository.java
  src/main/java/com/server/overtime/marker/service/MarkerService.java
Labels: feat
